backend/appTodo/api/v1/urls.py
from django.urls import path

from . import views
from rest_framework import routers

app_name = "api-v1"

urlpatterns = [
    path('tehran_weather/', views.TehranWeatherAPIView.as_view())
]


router = routers.DefaultRouter()
router.register(r"jobs", views.JobViewSet, basename="jobs")
urlpatterns += router.urls

backend/appTodo/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from appTodo import views

app_name = "appTodo"

urlpatterns = [
    path("jobs/", views.JobsView.as_view(), name="jobs"),
    path("jobs/delete/<int:pk>/", views.JobDeleteView.as_view(), name="delete_job"),
    path("jobs/update/<int:pk>/", views.JobUpdateView.as_view(), name="update_job"),
    path("api/v1/", include("appTodo.api.v1.urls")),
    path("test_send_email/", views.test_send_email),
    path("test_delay_3/", views.test_delay_3),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from appBlog.sitemaps import BlogSitemap, StaticViewSitemap
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="appBlog & appTodo API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

sitemaps = {
    "blog": BlogSitemap,
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("appAccount.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("appBlog.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("todo/", include("appTodo.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "swagger/output.json/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

backend/appTodo/models.py
from django.db import models
from appAccount.models import Profile
from django.shortcuts import reverse


class Job(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    STATUS_CHOICES = (
        ("done", "done"),
        ("undone", "undone"),
    )
    status = models.CharField(max_length=6, choices=STATUS_CHOICES, default="undone")
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.pk) + ":" + str(self.name)

    def return_email(self):
        return self.user.user.email

    def get_absolute_api_url(self):
        return reverse("appTodo:api-v1:jobs-detail", kwargs={"pk": self.pk})

backend/appTodo/forms.py
from django import forms
from appTodo.models import Job


class JobForm(forms.ModelForm):
    class Meta:
        model = Job
        fields = ["user", "name", "status"]

backend/appTodo/api/v1/views.py
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.response import Response
from rest_framework.views import APIView

from appTodo.models import Job
from .serializers import JobSerializer
from rest_framework import viewsets
from .permissions import IsOwnerOrReadOnly
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend
from .pagination import JobListPagination
from .filters import JobListFilter
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
import requests
from time import sleep


class JobViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = JobSerializer
    queryset = Job.objects.all()
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    ]
    filterset_class = JobListFilter
    search_fields = ["name"]
    ordering_fields = ["created_date"]
    pagination_class = JobListPagination

    @method_decorator(cache_page(60))
    def dispatch(self, request, *args, **kwargs):
        return super().dispatch(request, *args, **kwargs)


def get_weather(city_name):
    base_url = 'http://api.weatherapi.com/v1/current.json'
    params = {'q': city_name, 'key': 'e4e2692b7e03481e86692308241602'}

    try:
        response = requests.get(base_url, params=params)
        data = response.json()
        if response.status_code == 200:
            weather_info = {
                'temperature': data['current']['temp_c'],
                'condition': data['current']['condition']['text'],
            }
            return weather_info
        else:
            return response.status_code
    except requests.exceptions.RequestException as e:
        print('exception error')
        print(e)
        return None


class TehranWeatherAPIView(APIView):

    # caching for 20 minutes
    @method_decorator(cache_page(1200))
    def get(self, request, format=None):
        sleep(4)
        weather_info = get_weather('Tehran')
        return Response({'detail': weather_info})

backend/appTodo/views.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import ListView, DeleteView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from appTodo.models import Job
from appTodo.forms import JobForm
import requests
# from django.core.cache import cache
from django.views.decorators.cache import cache_page
from . import tasks


class JobsView(LoginRequiredMixin, ListView):
    template_name = "appTodo/job_list.html"
    context_object_name = "jobs"

    def get_queryset(self):
        return Job.objects.filter(user=self.request.user.profile).order_by(
            "-created_date"
        )

    def post(self, request):
        form = JobForm(self.request.POST)
        if form.is_valid():
            form.save()
        return redirect("appTodo:jobs")


class JobDeleteView(LoginRequiredMixin, DeleteView):
    success_url = reverse_lazy("appTodo:jobs")
    model = Job


class JobUpdateView(LoginRequiredMixin, UpdateView):
    template_name = "appTodo/job_update.html"
    model = Job
    fields = ["name", "status"]
    success_url = "/todo/jobs/"


# for background processing learning
def test_send_email(request):
    tasks.task2.delay()
    return HttpResponse("<h1>email sent</h1>")


# for learning cache usage
# def test_delay_3(request):
#     if cache.get('test_delay_3') is None:
#         response = requests.get('https://de1316b2-9246-42d9-9225-609e057b47ca.mock.pstmn.io/test/delay/3')
#         cache.set('test_delay_3', response.json(), 30)
#     return JsonResponse(cache.get('test_delay_3'))
@cache_page(30)
def test_delay_3(request):
    response = requests.get('https://de1316b2-9246-42d9-9225-609e057b47ca.mock.pstmn.io/test/delay/3')
    return JsonResponse(response.json())

backend/templates/appTodo/job_list.html
{% extends 'appBlog/_base.html' %}

{% block form_class %}
    d-none
{% endblock %}

{% block content %}
    <div class="container text-center">

        <form method="post" action="" class="my-5">
            {% csrf_token %}
            <label>Enter your job:</label>
              <select name="user" required id="id_user" hidden="hidden">
                <option value="{{ request.user.profile.pk }}"></option>
            </select>

             <input type="text" name="name" maxlength="100" required id="id_name">
            <select name="status" id="id_status">
                <option value="done">Done</option>
                <option value="undone">Undone</option>
            </select>

            <input type="submit" class="btn btn-primary" value="submit">
        </form>

        {% if jobs %}
    <table class="table my-5">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Job</th>
          <th scope="col">Status</th>
          <th scope="col">Created Date</th>
          <th scope="col">Delete</th>
        </tr>
      </thead>
      <tbody>
            {% for job in jobs %}
        <tr>
          <td><a href="{% url 'appTodo:update_job' job.pk %}">{{ job.name }}</a></td>
            {% if job.status == 'done' %}
                <td class="text-success">{{ job.status }}</td>
            {% else %}
                <td class="text-danger">{{ job.status }}</td>
            {% endif %}
          <td>{{ job.created_date }}</td>
          <td>
              <form method="POST" action="{% url "appTodo:delete_job" job.pk %}">
                {% csrf_token %}<input type="submit" value="X" class="btn btn-danger text-white">
            </form>

          </td>
        </tr>
            {% endfor %}
      </tbody>
</table>
        {% endif %}
    </div>

{% endblock %}

backend/templates/appTodo/job_update.html
{% extends 'appBlog/_base.html' %}

{% block form_class %}
    d-none
{% endblock %}

{% block content %}
    <div class="container text-center">

        <form method="post" action="" class="my-5">
            {% csrf_token %}
            <h2>Update your job:</h2>
              {{ form }}
{#             <input type="text" name="name" maxlength="100" required id="id_name">#}

            <input type="submit" class="btn btn-primary" value="submit">
        </form>

    </div>

{% endblock %}