backend/appAccount/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = "appAccount"

urlpatterns = [
    path("login/", views.LogInView.as_view(), name="login"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("api/v1/", include("appAccount.api.v1.urls")),
    path("api/v2/", include("djoser.urls")),
    path("api/v2/", include("djoser.urls.jwt")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/appBlog/api/v1/urls.py
# from django.urls import path
from django.urls import path

from . import views

# from django.conf import settings
# from django.conf.urls.static import static
from rest_framework import routers

app_name = "api-v1"

# urlpatterns = [
#     path('posts/', views.PostList.as_view(), name='post_list'),
#     path('posts/<int:pk>/', views.PostDetail.as_view(), name='post_detail'),
#
#     path('blog/category/<str:category>/', views.BlogView.as_view(), name='blog_category'),
#     path('blog/tag/<str:tag>/', views.BlogView.as_view(), name='blog_tag'),
#     path('blog/author/<str:author>/', views.BlogView.as_view(), name='blog_author'),
#     path('blog/<int:pid>/', views.SingleView.as_view(), name='single'),
#
#     path('posts/', views.PostViewSet.as_view({'get': 'list', 'post': 'create'}), name='post_list'),
#     path('posts/<int:pk>/', views.PostViewSet.as_view({'get': 'retrieve', 'put': 'update', 'patch': 'partial_update',
#                                                        'delete': 'destroy'}), name='post_detail'),
# ]
#
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = [
    path('post_list_render_template/', views.PostListRenderTemplate.as_view(), name='post_list'),
]

router = routers.DefaultRouter()
router.register(r"posts", views.PostViewSet, basename="posts")
urlpatterns += router.urls

backend/appBlog/urls.py
from django.urls import path, include
from appBlog import views
from django.conf import settings
from django.conf.urls.static import static
from appBlog.feeds import LatestEntriesFeed

app_name = "appBlog"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("blog/", views.BlogView.as_view(), name="blog"),
    path(
        "blog/category/<str:category>/", views.BlogView.as_view(), name="blog_category"
    ),
    path("blog/tag/<str:tag>/", views.BlogView.as_view(), name="blog_tag"),
    path("blog/author/<str:author>/", views.BlogView.as_view(), name="blog_author"),
    path("blog/<int:pid>/", views.SingleView.as_view(), name="single"),
    # path('contact/', views.contact_view, name='contact'),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("rss/feed/", LatestEntriesFeed()),
    path("blog/api/v1/", include("appBlog.api.v1.urls")),
    path("blog/get_post_list_from_api", views.PostList.as_view()),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/appTodo/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from appTodo import views

app_name = "appTodo"

urlpatterns = [
    path("jobs/", views.JobsView.as_view(), name="jobs"),
    path("jobs/delete/<int:pk>/", views.JobDeleteView.as_view(), name="delete_job"),
    path("jobs/update/<int:pk>/", views.JobUpdateView.as_view(), name="update_job"),
    path("api/v1/", include("appTodo.api.v1.urls")),
    path("test_send_email/", views.test_send_email),
    path("test_delay_3/", views.test_delay_3),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from appBlog.sitemaps import BlogSitemap, StaticViewSitemap
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi

schema_view = get_schema_view(
    openapi.Info(
        title="appBlog & appTodo API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="MIT License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

sitemaps = {
    "blog": BlogSitemap,
    "static": StaticViewSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("appAccount.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", include("appBlog.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("__debug__/", include("debug_toolbar.urls")),
    path("summernote/", include("django_summernote.urls")),
    path("captcha/", include("captcha.urls")),
    path("todo/", include("appTodo.urls")),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "swagger/output.json/",
        schema_view.without_ui(cache_timeout=0),
        name="schema-json",
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
]

backend/appBlog/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager
from appAccount.models import Profile


class Post(models.Model):
    class Meta:
        db_table = "appBlog_post"

    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(Profile, on_delete=models.CASCADE)
    published_date = models.DateTimeField()
    status = models.BooleanField(default=False)
    views = models.IntegerField(default=0)
    image = models.ImageField(upload_to="appBlog/posts/images/", default="default.jpg")
    categories = models.ManyToManyField(
        "Category", db_table="appBlog_post_category", blank=True
    )
    tags = TaggableManager()

    def __str__(self):
        return str(self.id) + "-" + self.title

    def get_snippet(self):
        return self.content[0:10]

    def get_absolute_url(self):
        return reverse("appBlog:single", kwargs={"pid": self.id})

    def get_absolute_api_url(self):
        return reverse("appBlog:api-v1:posts-detail", kwargs={"pk": self.pk})


class Category(models.Model):
    class Meta:
        db_table = "appBlog_category"
        verbose_name = "category"
        verbose_name_plural = "categories"

    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=255, null=True, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    allowed = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.id) + "-" + self.subject

backend/appBlog/forms.py
from django import forms
from appBlog.models import Contact, Comment
from captcha.fields import CaptchaField


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Contact
        fields = "__all__"


class CommentForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Comment
        fields = ["post", "name", "email", "subject", "message"]

backend/appBlog/api/v1/views.py
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework.response import Response
from rest_framework.views import APIView
from django.core.paginator import Paginator
from appBlog.models import Post
from .serializers import PostSerializer
from rest_framework import viewsets
from .permissions import IsOwnerOrReadOnly
from rest_framework import filters
from django_filters.rest_framework import DjangoFilterBackend
from .pagination import PostListPagination
from .filters import PostListFilter


class PostViewSet(viewsets.ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    queryset = Post.objects.filter(status=True)
    filter_backends = [
        DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    ]
    # filterset_fields = ['categories', 'author']
    filterset_class = PostListFilter
    search_fields = ["title", "categories__name"]
    ordering_fields = ["published_date"]
    pagination_class = PostListPagination


class PostListRenderTemplate(APIView):
    renderer_classes = [TemplateHTMLRenderer]
    template_name = "appBlog/blog.html"

    def get(self, request, **kwargs):
        posts = Post.objects.filter(status=1).order_by("-published_date")
        if s := request.GET.get("search"):
            posts = posts.filter(title__contains=s)
        if a := kwargs.get("author"):
            posts = posts.filter(author__username=a)
        if c := kwargs.get("category"):
            posts = posts.filter(categories__name=c)
        if t := kwargs.get("tag"):
            posts = posts.filter(tags__name__icontains=t)

        posts = Paginator(posts, 3)
        page_number = request.GET.get("page", 1)
        # try:
        posts = posts.page(page_number)
        # except PageNotAnInteger:
        #     return redirect("appBlog:post_list")
        # except EmptyPage:
        #     return redirect("appBlog:post_list")

        return Response({'posts': posts})

backend/appBlog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import TemplateView, FormView
from appBlog.models import Post, Comment
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from appBlog.forms import ContactForm, CommentForm
from django.contrib import messages


class HomeView(TemplateView):
    template_name = "appBlog/index.html"


class BlogView(View):
    def get(self, request, **kwargs):
        posts = Post.objects.filter(status=1).order_by("-published_date")
        if s := request.GET.get("search"):
            posts = posts.filter(title__contains=s)
        if a := kwargs.get("author"):
            posts = posts.filter(author__username=a)
        if c := kwargs.get("category"):
            posts = posts.filter(categories__name=c)
        if t := kwargs.get("tag"):
            posts = posts.filter(tags__name__icontains=t)

        posts = Paginator(posts, 3)
        page_number = request.GET.get("page", 1)
        try:
            posts = posts.page(page_number)
        except PageNotAnInteger:
            return redirect("appBlog:post_list")
        except EmptyPage:
            return redirect("appBlog:post_list")

        context = {"posts": posts}
        return render(request, "appBlog/blog.html", context)


class SingleView(LoginRequiredMixin, View):
    def get(self, request, pid):
        form = CommentForm()
        post_id_list = [
            post.id for post in Post.objects.all().filter(status=1).order_by("id")
        ]
        post = Post.objects.get(id=pid)
        comments = Comment.objects.filter(post=post, allowed=True)
        try:
            next_post = Post.objects.get(id=post_id_list[post_id_list.index(pid) + 1])
        except:
            next_post = None
        try:
            if post_id_list.index(pid) - 1 == -1:
                raise ValueError
            previous_post = Post.objects.get(
                id=post_id_list[post_id_list.index(pid) - 1]
            )
        except:
            previous_post = None
        try:
            post.views += 1
            post.save()
        except:
            return redirect("appBlog:home")
        context = {
            "form": form,
            "post": post,
            "previous_post": previous_post,
            "next_post": next_post,
            "comments": comments,
        }
        return render(request, "appBlog/blog-single.html", context)

    def post(self, request, pid):
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Comment Saved.")
        else:
            messages.error(request, form.errors)
        return redirect("appBlog:single", pid=pid)


class ContactView(FormView):
    template_name = "appBlog/contact.html"
    form_class = ContactForm

    def form_valid(self, form):
        form.save()
        messages.success(self.request, "message saved successfully.")
        return redirect("appBlog:home")

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return redirect("appBlog:contact")


class AboutView(TemplateView):
    template_name = "appBlog/about.html"


class PostList(TemplateView):
    template_name = "appBlog/get_post_list_from_api.html"

backend/templates/appBlog/_base.html
{% load static %}
{% load compress %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta name="description" content="this is a test website to learn django and seo">

    <!-- Facebook -->
    <meta property="og:title" content="home page(django learning)">
    <meta property="og:description" content="this is a test website to learn django and seo">
    <meta property="og:image" content="https://testhostmtp.com/static/images/favicon.jpg">
    <meta property="og:url" content="https://testhostmtp.com">

    <!-- twitter -->
    <meta name="twitter:title" content="Add title here">
    <meta name="twitter:description" content="Add description here">
    <meta name="twitter:url" content="https://testhostmtp.com/static/images/favicon.jpg">
    <meta name="twitter:card" content="summary">


  <title>{% block title %}{% endblock %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

    <link rel="shortcut icon" type="image/jpg" href="{% static 'images/favicon.jpg' %}" >

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
    {% compress css %}
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">
    {% endcompress %}

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}">

  <!-- Template Main CSS File -->
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">




  <!-- =======================================================
  * Template Name: FlexStart
  * Updated: Jul 27 2023 with Bootstrap v5.3.1
  * Template url: https://bootstrapmade.com/flexstart-bootstrap-startup-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

<body>

  <!-- ======= Header ======= -->
  <header id="header" class="header fixed-top">
    <div class="container-fluid container-xl d-flex align-items-center justify-content-between">

      <a href="{% url 'appBlog:home' %}" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo.png' %}" alt="flexstart logo">
        <span>FlexStart</span>
      </a>

      <nav id="navbar" class="navbar">
        <ul>
          <li><a class="nav-link scrollto {% block home_active %}active{% endblock %}" href="{% url 'appBlog:home' %}">Home</a></li>
          <li><a class="nav-link scrollto {% block about_active %}{% endblock %}" href="{% url 'appBlog:about' %}">About</a></li>
          <li><a class="nav-link scrollto {% block blog_active %}{% endblock %}" href="{% url 'appBlog:blog' %}">Blog</a></li>
          <li><a class="nav-link scrollto {% block contact_active %}{% endblock %}" href="{% url 'appBlog:contact' %}">Contact</a></li>
          {% if request.user.is_authenticated %}
            <li><a class="nav-link scrollto" href="{% url 'appTodo:jobs' %}">Jobs</a></li>
            <li><a class="nav-link scrollto" href="{% url 'appAccount:logout' %}">Logout</a></li>
              <li class="nav-link scrollto">{{ request.user }}</li>
          {% else %}
            <li><a class="nav-link scrollto" href="{% url 'appAccount:login' %}">Login</a></li>
            <li><a class="nav-link scrollto" href="{% url 'appAccount:signup' %}">Sign Up</a></li>
        {% endif %}
        </ul>
        <i class="bi bi-list mobile-nav-toggle"></i>
      </nav><!-- .navbar -->

    </div>
  </header><!-- End Header -->
    <br>
    <br>
    <br>
    <br>
  {% block content %}
  {% endblock %}






  <!-- ======= Footer ======= -->
  <footer id="footer" class="footer">

    <div class="footer-newsletter">
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-12 text-center">
            <h4>Our Newsletter</h4>
            <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
          </div>
          <div class="col-lg-6">
            <form action="" method="post">
                {% csrf_token %}
              <input type="email" name="email"><input type="submit" value="Subscribe">
            </form>
          </div>
        </div>
      </div>
    </div>

    <div class="footer-top">
      <div class="container">
        <div class="row gy-4">
          <div class="col-lg-5 col-md-12 footer-info">
            <a href="index.html" class="logo d-flex align-items-center">
              <img src="{% static 'assets/img/logo.png' %}" alt="flexstart logo">
              <span>FlexStart</span>
            </a>
            <p>Cras fermentum odio eu feugiat lide par naso tierra. Justo eget nada terra videa magna derita valies darta donna mare fermentum iaculis eu non diam phasellus.</p>
            <div class="social-links mt-3">
              <a href="#" class="twitter"><i class="bi bi-twitter"></i></a>
              <a href="#" class="facebook"><i class="bi bi-facebook"></i></a>
              <a href="#" class="instagram"><i class="bi bi-instagram"></i></a>
              <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a>
            </div>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Home</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">About us</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Services</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-2 col-6 footer-links">
            <h4>Our Services</h4>
            <ul>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Design</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Web Development</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Product Management</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Marketing</a></li>
              <li><i class="bi bi-chevron-right"></i> <a href="#">Graphic Design</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-12 footer-contact text-center text-md-start">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br><br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong><span>FlexStart</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/flexstart-bootstrap-startup-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->


  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

  <!-- Vendor JS Files -->
  {% compress js file base %}
  <script src="{% static 'assets/vendor/purecounter/purecounter_vanilla.js' %}"></script>
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
  <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
  <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>



        <script src="{% static 'assets/js/vendor/jquery-2.2.4.min.js' %}"></script>
        <script src="{% static "assets/js/popper.min.js" %}"></script>
        <script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>


  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js' %}"></script>
    {% endcompress %}

    {% include 'appBlog/_modal-message.html' %}

</body>

</html>

backend/templates/appBlog/_blog-author-section.html
<h3 class="sidebar-title">Authors</h3>
<div class="sidebar-item categories">
    <ul>

        {% for author in authors %}
            <li><a href="{% url 'appBlog:blog_author' author  %}">{{ author }}</a></li>
        {% endfor %}
    </ul>
</div><!-- End sidebar categories-->

backend/templates/appBlog/_blog-category-section.html
<h3 class="sidebar-title">Categories</h3>
<div class="sidebar-item categories">
    <ul>

        {% for category, post_count in categories %}
            <li><a href="{% url 'appBlog:blog_category' category  %}">{{ category }} <span>{{ post_count }}</span></a></li>
        {% endfor %}
    </ul>
</div><!-- End sidebar categories-->

backend/templates/appBlog/_blog-last-3-posts.html
{% load static %}
{% load humanize %}

<!-- ======= Recent Blog Posts Section ======= -->
    <section id="recent-blog-posts" class="recent-blog-posts">

      <div class="container" data-aos="fade-up">

        <header class="section-header">
          <h2>Blog</h2>
          <p>Recent posts form our Blog</p>
        </header>

        <div class="row">

        {% for post in posts %}
          <div class="col-lg-4">
            <div class="post-box">
              <div class="post-img"><img src="{{ post.image.url }}" class="img-fluid" alt=""></div>
              <span class="post-date">{{ post.published_date|naturalday }}</span>
              <h3 class="post-title">{{ post.title }}</h3>
              <a href="{% url 'appBlog:single' post.id %}" class="readmore stretched-link mt-auto"><span>Read More</span><i class="bi bi-arrow-right"></i></a>
            </div>
          </div>
        {% endfor %}

        </div>

      </div>

    </section><!-- End Recent Blog Posts Section -->

backend/templates/appBlog/_blog-latest-posts-section.html
<h3 class="sidebar-title">Recent Posts</h3>
<div class="sidebar-item recent-posts">

    {% for post in posts %}
        <div class="post-item clearfix">
          <img src="{{ post.image.url }}" alt="">
          <h4><a href="{% url 'appBlog:single' post.id %}">{{ post.title }}</a></h4>
          <time datetime="">{{ post.published_date|date:'Y-m-d' }}</time>
        </div>
    {% endfor %}

</div><!-- End sidebar recent posts-->

backend/templates/appBlog/_blog-tag-section.html
<h3 class="sidebar-title">Tags</h3>
<div class="sidebar-item tags">
<ul>
        {% for tag in tags %}
            <a href="{% url 'appBlog:blog_tag' tag %}"><li>{{ tag }}</li></a>
        {% endfor %}

</ul>
</div>

backend/templates/appBlog/_modal-message.html
<!-- Modal -->
{% if messages %}
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">
    {% for m in messages %}
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-body {{ m.tags }}">
          <p>{{ m }}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    {% endfor %}

    </div>
  </div>


    <script>
                var myModal = new bootstrap.Modal(document.getElementById('myModal'), {})
                myModal.toggle()
    </script>
{#{% endif %}#}
{##}
{##}
{##}
{#{% if messages %}#}

{% endif %}

backend/templates/appBlog/about.html
{% extends 'appBlog/_base.html' %}
{% load static %}

{% block title %}
    about
{% endblock %}

{% block about_active %}active{% endblock %}
{% block home_active %}{% endblock %}


{% block content %}
    <main id="main">
        <!-- ======= About Section ======= -->
        <section id="about" class="about">

      <div class="container" data-aos="fade-up">
        <div class="row gx-0">

          <div class="col-lg-6 d-flex flex-column justify-content-center" data-aos="fade-up" data-aos-delay="200">
            <div class="content">
              <h3>Who We Are</h3>
              <h2>Expedita voluptas omnis cupiditate totam eveniet nobis sint iste. Dolores est repellat corrupti reprehenderit.</h2>
              <p>
                Quisquam vel ut sint cum eos hic dolores aperiam. Sed deserunt et. Inventore et et dolor consequatur itaque ut voluptate sed et. Magnam nam ipsum tenetur suscipit voluptatum nam et est corrupti.
              </p>
              <div class="text-center text-lg-start">
                <a href="#" class="btn-read-more d-inline-flex align-items-center justify-content-center align-self-center">
                  <span>Read More</span>
                  <i class="bi bi-arrow-right"></i>
                </a>
              </div>
            </div>
          </div>

          <div class="col-lg-6 d-flex align-items-center" data-aos="zoom-out" data-aos-delay="200">
            <img src="{% static 'assets/img/about.jpg' %}" class="img-fluid" alt="about image">
          </div>

        </div>
      </div>

    </section><!-- End About Section -->
    </main><!-- End #main -->
{% endblock %}